name: Publish npm package

on:
  push:
    branches:
      - main
    tags:
      - '!*'

permissions:
  contents: write
  packages: write

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          registry-url: https://npm.pkg.github.com
          scope: '@wintyo-github-packages'

      - name: Install
        run: yarn install

      - name: Build
        run: yarn build

      # publish可能かのステータスを見る（0が正常。1がエラー）
      - id: publishable
        name: Check Publishable
        run: "\
          npx can-npm-publish --verbose \
          && echo status=0 >> $GITHUB_OUTPUT \
          || echo status=1 >> $GITHUB_OUTPUT"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # publish可能(まだpublishされていないバージョン)ならpublishする
      - name: Publish npm package
        if: ${{ steps.publishable.outputs.status == 0 }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISHABLE: ${{ steps.publishable.outputs.status }}

      # package.jsonのバージョンをenvに登録する
      - id: package-version
        name: Register Package Version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> "$GITHUB_OUTPUT"

      # tagが振られてなかったら振る
      - name: Add Tag
        uses: pkgdeps/git-tag-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ steps.package-version.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: 'v'
